name: Build and Push Docker image

on:
  push:
    branches:
      - main
    tags:
      - "^[0-9]{4}\\.[0-1][0-9]\\.[0-3][0-9]$"
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: "Set Docker tag: push to main"
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "DOCKER_TAG=latest" >> $GITHUB_ENV

      - name: "Set Docker tag: push to tag"
        if: github.event_name == 'push' && contains(github.ref, 'tags')
        run: |
          echo "DOCKER_TAG=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: "Set Docker tag: pull request"
        if: github.event.pull_request
        run: |
          echo "DOCKER_TAG=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: sgibson91
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            sgibson91/${{ github.event.repository.name }}:${{ env.DOCKER_TAG }}
